FROM golang:1.26 AS builder

WORKDIR /app

COPY . .

ARG GIT_COMMIT=""
ARG GIT_TAG=""
ARG GIT_BRANCH=""
ARG VERSION=""

RUN if [ -z "$VERSION" ]; then \
    if [ -n "$GIT_TAG" ]; then VERSION="$GIT_TAG"; \
    else VERSION="${GIT_BRANCH}-${GIT_COMMIT}"; \
    fi; \
    fi && \
    go build -ldflags="-s -w -X main.Commit=${GIT_COMMIT} -X main.Version=${VERSION}" -o build/api ./api

RUN touch config-api.yml
RUN chmod +x build/api

FROM gcr.io/distroless/base-debian13:latest
WORKDIR /app

COPY --from=builder --chown=nonroot:nonroot /app/build/api .
COPY --from=builder --chown=nonroot:nonroot /app/config-api.yml .

USER nonroot

ENTRYPOINT ["/app/api"]